### ISSUE TITLE
Gra wiesza się po zabiciu wszystkich przeciwników.

### ISSUE THREAD

**Issue by mmilins** [dnipromv/retoosh#32]
Gdy zabijemy wszystkich przeciwników gra zawiesza się. Prawdopodobnie implementacja #13 może to naprawić.

**Comment by Nowan** [comment]
Nie tylko po zabiciu wszystkich przeciwników. Czasami też w momencie/niedługo po restarcie levela

**Comment by mmilins** [comment]
Verified.
